name: Clojure CI/CD

on:
  push:
    branches: [main]
    tags:
      - "v*" # This will trigger on any tag starting with 'v'
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install Clojure Tools
        uses: DeLaGuardo/setup-clojure@13.1
        with:
          cli: "latest"

      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2
            ~/.gitlibs
          key: ${{ runner.os }}-deps-${{ hashFiles('**/deps.edn') }}
          restore-keys: ${{ runner.os }}-deps-

      - name: Run Tests
        run: clojure -T:build test

      - name: Build Uberjar
        run: clojure -T:build ci

      - name: Upload Uberjar
        uses: actions/upload-artifact@v4
        with:
          name: uberjar
          path: target/cdk/*.jar

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: uberjar
          path: target/cdk

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/cdk/*.jar
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
