name: Clojure CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install Clojure Tools
        uses: DeLaGuardo/setup-clojure@13.1
        with:
          cli: "latest"

      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2
            ~/.gitlibs
          key: ${{ runner.os }}-deps-${{ hashFiles('**/deps.edn') }}
          restore-keys: ${{ runner.os }}-deps-

      - name: Run Tests
        run: clojure -T:build test

      - name: Build Uberjar
        run: clojure -T:build ci

      - name: Upload Uberjar
        uses: actions/upload-artifact@v4
        with:
          name: uberjar
          path: target/cdk/*.jar # Adjust path based on your project structure
